Before do
  ActiveRecord::Base.connection.execute("DROP TABLE IF EXISTS users;")
  ActiveRecord::Base.connection.execute("
    CREATE TABLE IF NOT EXISTS users(
      id SERIAL PRIMARY KEY,
      email character varying(255) DEFAULT ''::character varying NOT NULL,
      encrypted_password character varying(255) DEFAULT ''::character varying NOT NULL,
      reset_password_token character varying(255),
      reset_password_sent_at timestamp without time zone,
      remember_created_at timestamp without time zone,
      sign_in_count integer DEFAULT 0 NOT NULL,
      current_sign_in_at timestamp without time zone,
      last_sign_in_at timestamp without time zone,
      current_sign_in_ip character varying(255),
      last_sign_in_ip character varying(255),
      created_at timestamp without time zone,
      updated_at timestamp without time zone,
      first_name character varying(255) NOT NULL,
      last_name character varying(255) NOT NULL,
      profession character varying(255),
      website character varying(255),
      bio text,
      facebook character varying(255),
      twitter character varying(255),
      public boolean DEFAULT true,
      secondary_email character varying(255),
      birthday date,
      gender character varying(255),
      postal_code character varying(255),
      phone character varying(255),
      city character varying(255),
      address_street character varying(255),
      address_district character varying(255),
      state character varying(255),
      admin boolean,
      avatar character varying(255),
      availability bigint,
      skills integer,
      topics integer,
      funder boolean DEFAULT false,
      cpf character varying(255),
      address_extra character varying(255),
      address_number character varying(255),
      country character varying(255),
      CONSTRAINT proper_email CHECK (((email)::text ~* '([0-9a-zA-Z]+[-._+&amp;])*[0-9a-zA-Z_-]+@([-0-9a-zA-Z]+[.])+[a-zA-Z]{2,6}'::text)),
      CONSTRAINT proper_phone CHECK ((((phone)::text ~* '[(]{1}[0-9]{2}[)]{1} [0-9]{8,9}'::text) OR ((phone)::text = ''::text)))
    );
  ")
end
