# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Interest.create(title: "Ciência e Tecnologia")
Interest.create(title: "Crianças e adolescentes")
Interest.create(title: "Defesa do Consumidor")
Interest.create(title: "Direitos Humanos")
Interest.create(title: "Educação")
Interest.create(title: "Esportes, Lazer e Cultura")
Interest.create(title: "Indústria, Comércio e Emprego")
Interest.create(title: "Meio Ambiente e Direitos dos Animais")
Interest.create(title: "Obras Públicas e Infraestrutura")
Interest.create(title: "Orçamento e Fiscalização Financeira")
Interest.create(title: "Pessoas de terceira idade")
Interest.create(title: "Saúde e Drogas")
Interest.create(title: "Transportes e Trânsito")
Interest.create(title: "Turismo")

Skill.create(title: "Administração e Políticas Públicas")
Skill.create(title: "Artes plásticas e performances artísticas")
Skill.create(title: "Artesanato e trabalhos manuais")
Skill.create(title: "Ciências políticas")
Skill.create(title: "Design Gráfico")
Skill.create(title: "Design Web / UX")
Skill.create(title: "Direito")
Skill.create(title: "Economia / Econometria")
Skill.create(title: "Edição de Vídeo / Pós-produção")
Skill.create(title: "Engenharia de transportes e tráfego")
Skill.create(title: "Estatística")
Skill.create(title: "Filmagem")
Skill.create(title: "Fotografia")
Skill.create(title: "Intervenções Urbanas / Grafite")
Skill.create(title: "Jornalismo / Assessoria de imprensa")
Skill.create(title: "Línguas e tradução")
Skill.create(title: "Marketing / Publicidade")
Skill.create(title: "Meio ambiente e Sustentabilidade")
Skill.create(title: "Organização de mobilização de rua / Ocupações do espaço público")
Skill.create(title: "Pedagogia e compartilhamento de conhecimento")
Skill.create(title: "Produção cultural e eventos")
Skill.create(title: "Programação de softwares, aplicativos ou web")
Skill.create(title: "Serviço e Assistência Social")
Skill.create(title: "Sociologia / Antropologia")
Skill.create(title: "Urbanismo e planejamento urbano")
